### PR TITLE
Fix whole bunch of issues & update to 1.7.10

### PR DESCRIPTION
**Pull request by dries007**
See commit messages

### CODE REVIEW

**Comment by diesieben07** [comment]
Thank you :)

**Comment by dries007** [comment]
Hopefully it al works as intended

**Comment by diesieben07** [comment]
Well, it certainly won't make anything worse :P

**Comment by dries007** [comment]
:thumbsup: on that

**Comment by dries007** [comment]
BTW, Sorry about the screwed up formatting, I didn't know what to use so I left it as clean as possible.

**Pull request merged**
